#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

username=$(git config user.name)

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

if [ "$username" != "danielcgithub" ]; then
	echo -e "${RED}Username is $username , will run script to change to personal config.${NC}"
	until ~/workspaces/personalGit.sh
	do
		~/workspaces/personalGit.sh
	done
else
	echo "${GREEN}Nothing to do as username=$username ${NC}"

fi
