# ansible-playbook notify_and_handlers.yaml --extra-vars "myhosts=dummy gather=yes pkg=httpd"
- hosts: "{{ myhosts }}"
  gather_facts: "{{gather}}"
  tasks:
    - name: install '{{ pkg }}'
      yum:
        name: "{{ pkg }}"
        state: latest
      notify:
        - enable and start '{{ pkg }}'
  handlers:
    - name: enable and start '{{ pkg }}'
      service:
        name: "{{ pkg }}"
        enabled: yes
        state: restarted
