# ansible-playbook permit_root_login_without_password.yaml --extra-vars "myhost=dummy"
- hosts: "{ myhost}"
  tasks:
    - name: Set PermitRootLogin to without-password in /etc/ssh/sshd_config and restart sshd
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin without-password"
        state: present
      notify:
        - Restart sshd
  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted
